### 1. Виконати набір вправ.

#### 1) Вводиться число n. Вивести масив разміра nхn, в якому по діагоналі йдуть числа від 1 до n, а інші числа рівні 0

In [5]:
import numpy as np
n = int(input("N: "))
arr = np.diag(np.linspace(1, n, n, dtype = int))
print(arr)

N: 6
[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


#### 3) Вводяться 4 числа n, m, r, c. Вивести масив розміру n на m, в якому в кожному r -му рядку і в кожному c-му стовбчику стоять 0, а інші елементи дорівнюють 1.

In [4]:
import numpy as np
n = int(input("N: "))
m = int(input("M: "))
r = int(input("R: "))
c = int(input("C: "))
arr = np.ones((n,m), dtype = int)
for i in range(0,m,c):
    arr[:,i] = 0
for i in range(0,n,r):
    arr[i,:] = 0
print(arr)

N: 6
M: 7
R: 2
C: 3
[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]


#### 4) Вводяться числа n і m. Вивести масив розміру n на m, в якому у першому рядку (рядок з нулевим індексом) йдуть числа від 0 до m-1, а всі інші елементи матриці дорівнюють 0.

In [3]:
n = int(input("N: "))
m = int(input("M: "))
arr = np.zeros((n,m), dtype = int)
arr[0,:] = np.arange(0,m,1)
print(arr)

N: 4
M: 10
[[0 1 2 3 4 5 6 7 8 9]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


#### 6) З клавіатури вводиться масив. Замінити всі ненульові елементи на - 1.

In [1]:
arr = np.array(input().split()).astype(int)
a = arr.nonzero()
arr[a] = -1
print(arr)

3 4 0 9 7 0 6 0 4 0 3
[-1 -1  0 -1 -1  0 -1  0 -1  0 -1]


#### 10) Вводиться числа n i m. Створити масив випадкових значень n на m і обчислити мінімальне, максимальне значення, середнє та середньо квадратичне відхилення, округлене до 3 знаків після коми

In [6]:
n = int(input("N: "))
m = int(input("M: "))
arr = np.random.random((n,m))
print(arr)
print("Min:", arr.min())
print("Max:", arr.max())
print("Average:", arr.mean())
print("Desp:", arr.var())

N: 3
M: 6
[[0.70986842 0.61564516 0.06023362 0.63939652 0.73152519 0.39907256]
 [0.64912991 0.32169217 0.93513842 0.778647   0.71084477 0.14132287]
 [0.59781364 0.9700961  0.9110064  0.34978086 0.57302746 0.41008916]]
Min: 0.06023362373707253
Max: 0.9700960970779678
Average: 0.583573901990176
Desp: 0.06321703364173611


#### 12) Створити масив одиниць розміром n х n та створити в ньому «рамку», сформовану з 0.

In [9]:
n = int(input("N: "))
arr = np.zeros((n,n))
arr[1:-1,1:-1] = 1
print(arr)

N: 6
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 15) Розмістити на полі 8х8 0 та одиниці в шахматному порядку, використовуючи функцію numpy tile().

In [10]:
arr = np.zeros((8,8), dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 17) Заповнити вектор значеннями від 0 до n. Всі значення, що більші за n/2 та менші за 3n/4 замінити нулями

In [12]:
n = int(input("N: "))
arr = np.arange(n+1)
arr[((n/2) <= arr) & (arr <= (3*n/4))] = 0
print(arr)

N: 15
[ 0  1  2  3  4  5  6  7  0  0  0  0 12 13 14 15]


#### 18) Заповнити вектор значеннями від 0 до n. Замінити знаки для всіх значеннь, що менші за n/2 та більші за 3n/4 на протилежні

In [13]:
n = int(input("N: "))
arr = np.arange(n+1)
arr[((n/2) > arr)] *= -1
arr[(arr > (3*n/4))] *= -1
print(arr)

N: 15
[  0  -1  -2  -3  -4  -5  -6  -7   8   9  10  11 -12 -13 -14 -15]


#### 22) Ввести числа n і m. Згенерувати матрицю n на n випадкових цілих елементів з діапазону [0, m]. Замінити всі максимальні елементи цієї матриці на протилежні за знаком.

In [15]:
n = int(input("N: "))
m = int(input("M: "))
arr = np.random.randint(0, m, (n,n))
print("Изначальная матрица: ")
print(arr)
arr[arr[:,:] == arr.max()] *= -1
print("Матрица после изменений: ")
print(arr)

N: 5
M: 10
Изначальная матрица: 
[[0 3 1 7 9]
 [4 6 3 1 2]
 [4 1 0 0 1]
 [8 9 0 7 2]
 [4 6 0 4 8]]
Матрица после изменений: 
[[ 0  3  1  7 -9]
 [ 4  6  3  1  2]
 [ 4  1  0  0  1]
 [ 8 -9  0  7  2]
 [ 4  6  0  4  8]]


### 2. Розв’язати систему за допомогою формул Крамера і виконати перевірку за допомогою матричного множення та функції numpy.linalg.solve().

In [16]:
A = np.array([[1,5,3,-4],[3,1,-2,0],[5,-7,0,10],[0,3,-5,0]])
B = np.array([20,9,-9,1])
Aob = np.linalg.inv(A)
print("Обратная матрица\n",Aob, "\n")
print("X = B * A^(-1)\n",Aob.dot(B), "\n")
print("Проверка: ")
np.linalg.solve(A,B)
np.allclose((Aob.dot(B)), np.linalg.solve(A,B), rtol=0, atol=1e-7)

Обратная матрица
 [[ 0.01587302  0.31746032  0.00634921 -0.11746032]
 [ 0.23809524 -0.23809524  0.0952381   0.23809524]
 [ 0.14285714 -0.14285714  0.05714286 -0.05714286]
 [ 0.15873016 -0.32539683  0.16349206  0.22539683]] 

X = B * A^(-1)
 [ 3.  2.  1. -1.] 

Проверка: 


True

### 3. Обчислити значення матричного виразу.

In [17]:
A = np.array([[5, 2, 0],[10, 4, 1],[7, 3, 2]])
B = np.array([[3, 6, -1],[-1, -2, 0],[2, 1, 3]])

res = np.dot((A - np.linalg.matrix_power(B, 2)),(2*A + B))
print(res)

[[  91   64   32]
 [ 257  146    1]
 [-322 -135  -51]]


### 4. Розв’язати рівняння за допомогою оберненої матриці і виконати перевірку за допомогою матричного множення та функції numpy.linalg.solve().

In [18]:
print("A * X = B")
A = np.array([[2, 3, 1],[4, -1, 0],[0, 1, 2]])
B = np.array([[9, 8, 7],[2, 7, 3],[4, 3, 5]])
print("\nX = A^(-1) * B")
X = np.dot(np.linalg.inv(A), B)
print(X)
print("\nПроверка:")
print(np.linalg.solve(A,B),"\n")
np.allclose((np.dot(np.linalg.inv(A), B)), np.linalg.solve(A,B), rtol=0, atol=1e-7)

A * X = B

X = A^(-1) * B
[[1. 2. 1.]
 [2. 1. 1.]
 [1. 1. 2.]]

Проверка:
[[1. 2. 1.]
 [2. 1. 1.]
 [1. 1. 2.]] 



True