In [4]:
import numpy as np
n = int(input())
arr = np.diag(np.linspace(1, n, n, dtype = int))
print(arr)

7
[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 7]]


## 3

In [10]:
import numpy as np
n = int(input())
m = int(input())
r = int(input())
c = int(input())
arr = np.ones((n,m), dtype = int)
for i in range(0,m,c):
    arr[:,i] = 0
for i in range(0,n,r):
    arr[i,:] = 0
print(arr)

6
7
2
3
[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]


## 4

In [106]:
import numpy as np
n = int(input())
m = int(input())
arr = np.zeros((n,m), dtype = int)
for i in range(m):
    arr[0,i] = i
print(arr)

6
6
[[0 1 2 3 4 5]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


## 6

In [44]:
import numpy as np
arr = np.array(input().split()).astype(int)
a = arr.nonzero()
for i in a:
    arr[i] = -1
print(arr)

3 4 0 9 7 0 6 0 4 0 3
[-1 -1  0 -1 -1  0 -1  0 -1  0 -1]


## 10

In [46]:
import numpy as np
n = int(input())
m = int(input())
arr = np.random.random((n,m))
print(arr)
print("Min:", arr.min())
print("Max:", arr.max())
print("Average:", arr.mean())
print("Desp:", arr.var())

6
3
[[0.23067015 0.92885413 0.8149258 ]
 [0.77893341 0.8456192  0.28309344]
 [0.84372253 0.92961273 0.3247148 ]
 [0.75465974 0.88371962 0.49626353]
 [0.49674795 0.93456566 0.773234  ]
 [0.61224895 0.02301114 0.97628913]]
Min: 0.023011137403109116
Max: 0.9762891286431292
Average: 0.6628269958431542
Desp: 0.07770766694362145


## 12

In [48]:
import numpy as np
n = int(input())
arr = np.zeros((n,n))
arr[1:-1,1:-1] = 1
print(arr)

6
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


## 15

In [64]:
arr = np.zeros((8,8), dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 17

In [66]:
n = int(input())
arr = np.arange(n+1)
arr[((n/2) <= arr) & (arr <= (3*n/4))] = 0
print(arr)

10
[ 0  1  2  3  4  0  0  0  8  9 10]


## 18

In [67]:
n = int(input())
arr = np.arange(n+1)
arr[((n/2) > arr)] *= -1
arr[(arr > (3*n/4))] *= -1
print(arr)

10
[  0  -1  -2  -3  -4   5   6   7  -8  -9 -10]


## 22

In [80]:
n = int(input())
m = int(input())
arr = np.random.randint(0, m, (n,n))
print("Изначальная матрица: ")
print(arr)
arr[arr[:,:] == arr.max()] *= -1
print("Матрица после изменений: ")
print(arr)

5
10
Изначальная матрица: 
[[7 4 7 9 2]
 [7 3 7 1 0]
 [3 0 1 3 5]
 [8 2 4 6 1]
 [5 2 0 9 6]]
Матрица после изменений: 
[[ 7  4  7 -9  2]
 [ 7  3  7  1  0]
 [ 3  0  1  3  5]
 [ 8  2  4  6  1]
 [ 5  2  0 -9  6]]


## 2. Решение методом Крамера

In [84]:
A = np.array([[1,5,3,-4],[3,1,-2,0],[5,-7,0,10],[0,3,-5,0]])
B = np.array([20,9,-9,1])
Aob = np.linalg.inv(A)
print("Обратная матрица\n",Aob, "\n")
print("X = B * A^(-1)\n",Aob.dot(B), "\n")
print("Проверка: ")
np.linalg.solve(A,B)
np.allclose((Aob.dot(B)), np.linalg.solve(A,B), rtol=0, atol=1e-7)

Обратная матрица
 [[ 0.01587302  0.31746032  0.00634921 -0.11746032]
 [ 0.23809524 -0.23809524  0.0952381   0.23809524]
 [ 0.14285714 -0.14285714  0.05714286 -0.05714286]
 [ 0.15873016 -0.32539683  0.16349206  0.22539683]] 

X = B * A^(-1)
 [ 3.  2.  1. -1.] 

Проверка: 


True

## 3. Матричное выражение

In [101]:
A = np.array([[5, 2, 0],[10, 4, 1],[7, 3, 2]])
B = np.array([[3, 6, -1],[-1, -2, 0],[2, 1, 3]])

res = np.dot((A - np.linalg.matrix_power(B, 2)),(2*A + B))
print(res)

[[  91   64   32]
 [ 257  146    1]
 [-322 -135  -51]]


## 4. Обратная матрица

In [105]:
print("A * X = B")
A = np.array([[2, 3, 1],[4, -1, 0],[0, 1, 2]])
B = np.array([[9, 8, 7],[2, 7, 3],[4, 3, 5]])
print("\nX = A^(-1) * B")
X = np.dot(np.linalg.inv(A), B)
print(X)
print("\nПроверка:")
print(np.linalg.solve(A,B),"\n")
np.allclose((np.dot(np.linalg.inv(A), B)), np.linalg.solve(A,B), rtol=0, atol=1e-7)

A * X = B

X = A^(-1) * B
[[1. 2. 1.]
 [2. 1. 1.]
 [1. 1. 2.]]

Проверка:
[[1. 2. 1.]
 [2. 1. 1.]
 [1. 1. 2.]] 



True